name: live_wallpaper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.8.2
  async_wallpaper: ^2.0.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.4
  lottie: ^3.0.0
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.3
  share_plus: ^7.2.1
  flutter_rating_bar: ^4.0.1
  in_app_review: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/video1.mp4
    - assets/video2.mp4
    - assets/video3.mp4
    - assets/video4.mp4
    - assets/video5.mp4
    - assets/video6.mp4
    - assets/video7.mp4
    - assets/video8.mp4
    - assets/video9.mp4
    - assets/video10.mp4
    - assets/video11.mp4
    - assets/images/
    - assets/lottie/