name: live_wallpaper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.1

dependencies:
  flutter:
    sdk: flutter
  async_wallpaper: ^2.1.0
  path_provider: ^2.1.5
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/video1.mp4
    - assets/video2.mp4
    - assets/video3.mp4